name: Build and Push to Google Artifact Registry

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SVC_KEY }}'

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker northamerica-northeast2-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: northamerica-northeast2-docker.pkg.dev/vaulted-anthem-465400-d1/hello-world-webapp-repo/hello-world-webapp:latest
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy hello-world-webapp \
            --image=northamerica-northeast2-docker.pkg.dev/vaulted-anthem-465400-d1/hello-world-webapp:latest \
            --region=northamerica-northeast2 \
            --platform=managed \
            --allow-unauthenticated